import { Avatar, Button, Chip, Paper, Skeleton, Stack, Table, TableBody, TableCell, TableHead, TablePagination, TableRow, Typography } from '@mui/material';
import { Student } from '../types';

export function StudentTable({ rows, total, loading, page, pageSize, onPageChange, onPageSizeChange, onDelete }: { rows: Student[]; total: number; loading: boolean; page: number; pageSize: number; onPageChange: (v: number) => void; onPageSizeChange: (v: number) => void; onDelete: (id: string) => void }) {
  if (loading) return <Stack spacing={1.2}>{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} variant="rounded" height={42} />)}</Stack>;
  if (!rows.length) return <Paper sx={{ p: 3 }}><Typography>No students found. Try changing search/filter.</Typography></Paper>;
  return <Paper><Table size="small"><TableHead><TableRow><TableCell>Student Photo</TableCell><TableCell>Admission Number</TableCell><TableCell>Roll Number</TableCell><TableCell>Student Name</TableCell><TableCell>Class</TableCell><TableCell>Section</TableCell><TableCell>Gender</TableCell><TableCell>Mobile</TableCell><TableCell>Student Type</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>
    {rows.map((r)=><TableRow key={r.id}><TableCell><Avatar src={r.photoUrl}>{r.firstName[0]}</Avatar></TableCell><TableCell>{r.academic.admissionNo}</TableCell><TableCell>{r.academic.rollNo}</TableCell><TableCell>{r.fullName}</TableCell><TableCell>{r.academic.classId}</TableCell><TableCell>{r.academic.sectionId}</TableCell><TableCell>{r.gender}</TableCell><TableCell>{r.mobile}</TableCell><TableCell>{r.academic.studentType}</TableCell><TableCell><Chip size="small" label={r.status} color={r.status==='active'?'success':'default'} /></TableCell><TableCell><Stack direction="row" spacing={0.5} flexWrap="wrap"><Button size="small">View</Button><Button size="small">Edit</Button><Button size="small" color="error" onClick={()=>onDelete(r.id)}>Delete</Button><Button size="small">Promote</Button><Button size="small">Print ID</Button></Stack></TableCell></TableRow>)}
  </TableBody></Table><TablePagination component="div" count={total} page={page} onPageChange={(_, p) => onPageChange(p)} rowsPerPage={pageSize} onRowsPerPageChange={(e) => onPageSizeChange(Number(e.target.value))} rowsPerPageOptions={[5,10,25,50]} /></Paper>;
}
